name: Code analysis check

on:
  workflow_call:

permissions: {}

jobs:
  style:
    name: Code style check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 50
          submodules: recursive

      - name: Install Flutter
        uses: subosito/flutter-action@v2.21.0
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Run dependency validator
        run: |
          dart pub global activate dependency_validator
          dart pub global run dependency_validator:dependency_validator

      - name: Verify formatting
        run: dart format --set-exit-if-changed .

      - name: Analyze project
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: true
          fatal-warnings: true
